spring:
  application:
    name: spring-data-jpa
  datasource:
    url: jdbc:postgresql://localhost:5432/data_jpa
    username: postgres
    password: itstitst
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true

server:
  port: 8081  # Set the application to run on port 8081
