logging:
  level:
    root: INFO
    com.microservices.logs: DEBUG

# Custom log file location
  file:
    name: logs/app-log.log

# Additional log configurations can be added here based on requirements.
